### ISSUE TITLE
Dropdown blocks aren't duplicable / saveable after changing dropdown value from the default setting

### ISSUE THREAD

**Issue by pmalacho-mit** [mitmedialab/prg-extension-boilerplate#87]
Previous commits (https://github.com/mitmedialab/prg-extension-boilerplate/commit/be6406b1222358e4084e8a7c0128b125061b0ebe) have been necessary to fix issues where numbered dropdown options cause issues. 

In short, if a collection of menu items used numbers as their 'value' field (e.g. `value: 4`) then, once a user modified the value of that menu, that block could no longer be duplicated without errors (pasted immediately below). Also, if a project was saved with that block, that project could no longer be loaded because of the same, mysterious DOM errors. This error could be fixed by instead using a string representation of that same number (e.g. `value: '4'` ).

> Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at e (blockly_compressed_vertical.js:446:1)
    at Object../node_modules/imports-loader/index.js?this=>window!./node_modules/exports-loader/index.js?Blockly&goog!./node_modules/scratch-blocks/blockly_compressed_vertical.js.goog.dom.append_ (blockly_compressed_vertical.js:446:1)
    at Object../node_modules/imports-loader/index.js?this=>window!./node_modules/exports-loader/index.js?Blockly&goog!./node_modules/scratch-blocks/blockly_compressed_vertical.js.goog.dom.createDom_ (blockly_compressed_vertical.js:445:1)
    at Object../node_modules/imports-loader/index.js?this=>window!./node_modules/exports-loader/index.js?Blockly&goog!./node_modules/scratch-blocks/blockly_compressed_vertical.js.goog.dom.createDom (blockly_compressed_vertical.js:444:1)
    at Object../node_modules/imports-loader/index.js?this=>window!./node_modules/exports-loader/index.js?Blockly&goog!./node_modules/scratch-blocks/blockly_compressed_vertical.js.Blockly.Xml.fieldToDom_ (blockly_compressed_vertical.js:925:1)
    at Object../node_modules/imports-loader/index.js?this=>window!./node_modules/exports-loader/index.js?Blockly&goog!./node_modules/scratch-blocks/blockly_compressed_vertical.js.Blockly.Xml.allFieldsToDom_ (blockly_compressed_vertical.js:925:1)
    at Object../node_modules/imports-loader/index.js?this=>window!./node_modules/exports-loader/index.js?Blockly&goog!./node_modules/scratch-blocks/blockly_compressed_vertical.js.Blockly.Xml.blockToDom (blockly_compressed_vertical.js:926:1)
    at Object../node_modules/imports-loader/index.js?this=>window!./node_modules/exports-loader/index.js?Blockly&goog!./node_modules/scratch-blocks/blockly_compressed_vertical.js.Blockly.Xml.blockToDom (blockly_compressed_vertical.js:927:1)
    at blockly_compressed_vertical.js:785:1

@DolevArtzi helped us discover that this issue is more pervasive so we're going to have to investigate. 

~~It seems like this commit is the culprit: https://github.com/mitmedialab/prg-extension-boilerplate/commit/c354423d38213078beb0f0d02c3391529489638f~~ @DolevArtzi tested downgrading json package and it had no effect

**Comment by randi-c-dubs** [comment]
Problem that led to json5 bump arose around August 2021 (failed builds) and was fixed around September 2021 (successful build): https://github.com/mitmedialab/prg-extension-boilerplate/actions?page=8

**Comment by DolevArtzi** [comment]
https://github.com/mitmedialab/prg-extension-boilerplate/commit/eb160cf1f8b4bf3863fdc07b1c63634c3690deb5 (resolved on `dev-machineaudition`)

**Comment by pmalacho-mit** [comment]
Hey @DolevArtzi -- I actually want to keep this one open, since the underlying issue still exists (but glad it's fixed for music creation blocks!!)
